language: go
go:
    - 1.6
#    - tip

go_import_path: github.com/versent/unicreds

install:
    - echo noop

env:
    - "PATH=/home/travis/gopath/bin:$PATH"

script:
    - go get -u github.com/golang/lint/golint
    - go get -u golang.org/x/tools/cmd/goimports
    - go get -u github.com/mitchellh/gox
    - go get
    - golint ./...
    - make updatedeps
    - make test
    - make dist

matix:
    fast_finish: true
    allow_failures:
        - go: tip
